A="\e[31m"
B="\e[1;${A}"
C="\e[0m"
D="\e[34m"
echo ""
echo ""
echo -e "${B}--[ ALBEDO CLOUD9 STORE ]--${C}"
echo ""
echo -e "${A}  --[ CREATE ACCOUNT ]--${C}"
echo -e "${D}"
z="
";NBz='p 2';Iz='loud';CBz='MASI';PBz='tp:/';Lz=' USE';Dz='ME b';ABz=' NJI';Nz='E';Cz='ERNA';wBz='ome/';mz=' clo';jBz='ING"';Xz=' "IP';dBz=' "CL';LBz='I NJ';cBz='ORD"';Yz=' : (';XBz='AME"';FBz='!"';BBz='NG! ';fz='RT b';ez=' "PO';iBz='MU J';ECz='null';fBz='AJA ';MBz='ING!';rBz='USER';GBz='slee';Uz=' PAS';Mz='RNAM';Ez='aru:';KBz='LESA';kz=' "FO';pBz='$IP ';Sz='sswo';CCz=' > /';ZBz='RD :';vBz='w /h';tz='is a';Fz=' (us';aBz=' "$P';qBz='-a $';uBz='RD -';oz='(kal';gBz='TERM';OBz=' "ht';hBz='INAL';Bz=' "US';Vz='SWOR';Kz='read';iz=' POR';DCz='dev/';yBz='E/al';dz=' IP';qz='k ng';EBz='OSES';DBz='H PR';YBz='"';Az='echo';lz='LDER';kBz='node';nBz=' -p ';lBz=' x/s';hz='rt c';rz='erti';oBz=' -l ';jz='T_C9';WBz='SERN';xBz='$USE';mBz='r.js';Wz='D';vz=' FOL';yz='NGGU';az='ps/s';JBz=' "SE';Hz='me c';tBz=':$PA';IBz=' ""';Jz='9):"';pz='o ga';gz=' (po';Gz='erna';HBz='p 5';bBz='ASSW';xz=' "TU';uz='ja c';Zz='ip v';wz='DER';TBz='""';sz=' tul';SBz='$POR';ACz='bedo';eBz='OSE ';Qz='RD b';cz='r):"';FCz=' 2>&';Tz='rd c';VBz=' "$U';UBz='ME :';QBz='/"$I';nz='ud9:';RBz='P":"';Oz=' "PA';BCz='-$FO';Pz='SSWO';Rz=' (pa';GCz='1';bz='erve';sBz='NAME';
eval "$Az$Bz$Cz$Dz$Ez$Fz$Gz$Hz$Iz$Jz$z$Kz$Lz$Mz$Nz$z$Az$Oz$Pz$Qz$Ez$Rz$Sz$Tz$Iz$Jz$z$Kz$Uz$Vz$Wz$z$Az$Xz$Yz$Zz$az$bz$cz$z$Kz$dz$z$Az$ez$fz$Ez$gz$hz$Iz$Jz$z$Kz$iz$jz$z$Az$kz$lz$mz$nz$oz$pz$qz$rz$sz$tz$uz$Iz$Jz$z$Kz$vz$wz$z$Az$xz$yz$ABz$BBz$CBz$DBz$EBz$FBz$z$GBz$HBz$z$Az$IBz$z$Az$JBz$KBz$LBz$MBz$FBz$z$GBz$NBz$z$Az$IBz$z$Az$OBz$PBz$QBz$RBz$SBz$jz$TBz$z$Az$IBz$z$Az$Bz$Cz$UBz$VBz$WBz$XBz$YBz$z$Az$IBz$z$Az$Oz$Pz$ZBz$aBz$bBz$cBz$YBz$z$Az$IBz$z$Az$dBz$eBz$fBz$gBz$hBz$iBz$jBz$z$kBz$lBz$bz$mBz$nBz$SBz$jz$oBz$pBz$qBz$rBz$sBz$tBz$Pz$uBz$vBz$wBz$xBz$Mz$yBz$ACz$BCz$lz$CCz$DCz$ECz$FCz$GCz"
