A="\e[31m"
B="\e[1;${A}"
C="\e[0m"
D="\e[34m"
echo ""
echo ""
echo -e "${B}--[ ALBEDO CLOUD9 STORE ]--${C}"
echo ""
echo -e "${A}--[ CLOUD9 AUTO INSTALLER ]--${C}"
echo -e "${D}"
z="
";Az='echo';CBz='//gi';PBz='IGA)';yz='clon';Yz='ial ';Lz='TAMA';VBz='all-';kz='ubus';pz='/ins';nz='t.co';lz='erco';ABz='e ht';Wz='d-es';Cz='BEDO';rz='/mas';Tz='apt-';HBz='.git';Gz='L CL';Fz='STAL';ez='curl';oz='m/c9';Iz=' (BA';EBz='.com';MBz='fig.';Hz='OUD9';jz='gith';QBz='"';wz='h';uz='sh |';bz='y';RBz='cd x';az='js -';TBz='scri';sz='ter/';XBz='scre';FBz='/c9/';xz='git ';Zz='node';JBz='chmo';IBz=' x';LBz=' con';Oz='inst';mz='nten';Dz=' AUT';Xz='sent';iz='raw.';Nz='apt ';Bz=' "AL';Jz='GIAN';dz='UA)"';Kz=' PER';OBz=' KET';UBz='pts/';Qz='pyth';tz='all.';hz='s://';YBz='en';Uz='get ';KBz='d +x';SBz=' && ';cz=' KED';Pz='all ';NBz='sh';Mz=')"';BBz='tps:';Ez='O IN';Vz='buil';Sz='-y';vz=' bas';DBz='thub';gz='http';GBz='core';qz='tall';Rz='on2 ';WBz='sdk.';ZBz=' ""';fz=' -L ';
eval "$Az$Bz$Cz$Dz$Ez$Fz$Gz$Hz$Iz$Jz$Kz$Lz$Mz$z$Nz$Oz$Pz$Qz$Rz$Sz$z$Tz$Uz$Oz$Pz$Vz$Wz$Xz$Yz$Sz$z$Tz$Uz$Oz$Pz$Zz$az$bz$z$Az$Bz$Cz$Dz$Ez$Fz$Gz$Hz$Iz$Jz$cz$dz$z$ez$fz$gz$hz$iz$jz$kz$lz$mz$nz$oz$pz$qz$rz$sz$Oz$tz$uz$vz$wz$z$xz$yz$ABz$BBz$CBz$DBz$EBz$FBz$GBz$HBz$IBz$z$JBz$KBz$LBz$MBz$NBz$z$Az$Bz$Cz$Dz$Ez$Fz$Gz$Hz$Iz$Jz$OBz$PBz$QBz$z$RBz$SBz$TBz$UBz$Oz$VBz$WBz$NBz$z$XBz$YBz$z$Az$ZBz"
